### ISSUE TITLE
The Username is case sensitive and does not bring up profile info

### ISSUE THREAD

**Issue by tauheedul** [Common-Voice/sentence-collector#101]
If you login with an account and the username is all lower case. The profile loads successfully with a summary count of submitted and reviewed sentences.

If you login using mixed case username. It will allow you to login with the same password but the user profile will not load and it will ask you to re-review previously reviewed sentences. It's as though it thinks they are two different profiles.

See the difference logging in with the following...

originalusername
Vs
Originalusername

On an Android phone, the first letter of a text field is automatically made uppercase unless you manually change it to lower case. So this might become a common scenario.

**Comment by MichaelKohler** [comment]
Thanks for filing this issue. This is due to username actually being case sensitive. These are two different username, therefore two different profiles. This is how our backend works, and we won't be able to change that. In the long term, if this tool proves to provide value, we possibly will switch to Mozilla IAM, the same login mechanism as voice.mozilla.org for example uses. Then it's gonna be based on email, and that won't happen anymore.
