### ISSUE TITLE
Can't add language that was already once added and removed

### ISSUE THREAD

**Issue by Adrijaned** [Common-Voice/sentence-collector#271]
![Screenshot_20191202_195756](https://user-images.githubusercontent.com/22203805/69986662-2b7d2980-153e-11ea-8148-743cc9dba3ae.png)

**Comment by Adrijaned** [comment]
After adding one other language I haven't added before, the macedonian appeared together with it. Still quite confusing nevertheless.

**Comment by MichaelKohler** [comment]
Thanks for filing this, would be great if somebody wants to debug this further to see where exactly the error happens :)

**Comment by parshva-b** [comment]
@MichaelKohler, I would like to contribute towards resolving this issue. Can I claim it?

**Comment by MichaelKohler** [comment]
You got it!

**Comment by parshva-b** [comment]
@Adrijaned can you list steps to reproduce the error, because I tried the following 

![GIF](https://user-images.githubusercontent.com/39988731/72826059-23b84680-3c9e-11ea-9e1a-35c4783ad8d4.gif)

But Macedonian did not appear along with added language, I also tried adding language and removing it and checking if Macedonian was added. Been trying for 30 mins to reproduce the error.

@MichaelKohler, I also went through the code for adding language, everything seems to be running fine. (also language code for added language is already removed from language select list)

**Comment by MichaelKohler** [comment]
I was able to reproduce this when the issue was filed, but I don't remember exactly what I did. Now I somehow can't reproduce this anymore. @Adrijaned would be great to have more granular steps :)

**Comment by MichaelKohler** [comment]
@Adrijaned have you encountered this again? If not, let's close this.

**Comment by Adrijaned** [comment]
I have not encountered this issue since, so feel free to close, but, to be
fair, I haven't really opened the sentence collector website since tackling
Wikipedia and europarl imports. Either way this issue is not something many
people would encounter even if it was still in.

**Comment by MichaelKohler** [comment]
I've rewritten how the whole language adding and removing works in the feature/mysql branch. I'd say let's close this once we deploy that.

**Comment by MichaelKohler** [comment]
The infra work is now in the latest version which just got deployed: https://discourse.mozilla.org/t/action-required-new-sentence-collector-infrastructure-and-improvements/68759. This should not happen again.
