### ISSUE TITLE
Mistakes that usually occur in most sentences

### ISSUE THREAD

**Issue by jaspreet9339** [common-voice/sentence-collector#317]
These are words that slow down the speed of recording in Punjabi Language;-

Wrong Words-  ਵਿਚ, ਜਿਥੇ, ਉਥੇ, ਕੁੱਝ, ਕਿਥੇ, ਜਰੂਰੀ 
Correct Words- ਵਿੱਚ, ਜਿੱਥੇ. ਉੱਥੇ, ਕੁਝ, ਕਿੱਥੇ, ਜ਼ਰੂਰੀ

**Comment by MichaelKohler** [comment]
What language is that for?

**Comment by jaspreet9339** [comment]
Punjabi Language.These words are used again and again

**Comment by SeaLiteral** [comment]
I can't read Punjabi, but I have noticed two problems in another language, which also involves lots of misspelled words: Looking at the Danish sentences,

1: Our alphabet got a new letter, å, like 80 years ago. A lot of words that should be spelled with that letter appear with two a's instead. Probably because they were written before the spelling reform. Examples of sentences that should have å but have aa:
Instrumentet er saa lille, sagde Charlot. (correction: Instrumentet er så lille, sagde Charlot.)
Hele Orkestret havde staaet deroppe. (correction: Hele orkestret havde stået deroppe.)

2: I don't remember when the capitalization rules were changed, but those too were changed long ago. In fact, one of the sentences above has a capitalized noun that shouldn't be capitalized nowadays. More sentences with that:
Han så efter Etager, hvor der blev tændt op til Fest. (Han så efter etager, hvor der blev tændt op til fest.)
Han elskede de levninger, Moderen fik rundt i de "gode" Huse, hvor hun vaskede. (Han elskede de levninger, moderen fik rundt i de "gode" huse, hvor hun vaskede.)

Or should each language be a separate issue?

**Comment by MichaelKohler** [comment]
Just a quick drive-by here, haven't had much time to look closer into this, but from what I've read I think we could already do parts of that. Every language can have a validation file which will run on all uploaded sentences. Sentences that don't match will be rejected. Currently the categories are quite constrained, so we might need a new category for this (as I said, haven't looked closely at this one here). This is how it would need to be done: https://github.com/common-voice/sentence-collector/blob/main/server/lib/validation/VALIDATION.md

**Comment by MichaelKohler** [comment]
Validation rules can now have an arbitrary amount of rules and each of these rules can define their own error message. Therefore I'm going to close this as this can be solved by adding a validation for Punjabi. More information can be found on https://github.com/common-voice/sentence-collector/blob/main/server/lib/validation/VALIDATION.md.
