### ISSUE TITLE
Add basic sentence validation requirements

### ISSUE THREAD

**Issue by MichaelKohler** [Common-Voice/sentence-collector#33]
Currently there is a discussion going on on how to improve the quality of the sentences. There are a few requirements we will need to implement here. As this is still ongoing, consider this issue as a placeholder and it will be updated once we have the full list of decisions.

**Comment by nukeador** [comment]
To re-cap the last list we have:

- Numbers. There should be no digits in the source text because they can cause problems when read aloud. The way a number is read depends on context and might introduce confusion in the dataset. For example, the number “2409” could be accurately read as both “twenty-four zero nine” and “two thousand four hundred nine”.
- Abbreviations and Acronyms. Abbreviations and acronyms like “USA” or “ICE” should be avoided in the source text because they may be read in a way that does not coincide with their spelling. Additionally, there may be multiple accurate readings for a single abbreviation. For example, the acronym “ICE” could be pronounced “I-C-E” or as a single word.
- Punctuation. Special symbols and punctuation should only be included when absolutely necessary. For example, an apostrophe is included in English words like “don’t” and “we’re” and should be included in the source text, but it’s unlikely you’ll ever need a special symbol like “@” or “#.”
- Foreign letters. Letters must be valid in the language being spoken. For example, “ж” is a letter in the Russian alphabet but is never used in English and so should never appear in any English source text.

**Comment by MichaelKohler** [comment]
@nukeador will figure out how we could do the forth point, the rest I will implement rudimentary.

**Comment by MichaelKohler** [comment]
Created #35 for the fourth point so we can close this once I have implemented the rest.

**Comment by dabinat** [comment]
What about profanity?

**Comment by MichaelKohler** [comment]
@dabinat thanks for your input. Of course profanity is something we want to deal with as well. We will have a review process in place which should catch most of it. We'll see how this works out, theoretically we could also integrate a blacklist of words.
