### ISSUE TITLE
Sentences failing for Spanish

### ISSUE THREAD

**Issue by nukeador** [Common-Voice/sentence-collector#45]
I got some fails in these sentences and I'm not sure why:

> Filtered sentences due to requirements failing:
> 
> Una es más auténtica, mientras más se parece a lo que soñó de sí misma.
> 
> Soy el desesperado, la palabra sin ecos, el que lo perdió todo, y el que todo lo tuvo.
> 
> La niña era superdotada, con tan sólo 2 años ya sabía leer.

**Comment by Txopi** [comment]
The last sentence has a number (2).

**Comment by MichaelKohler** [comment]
And the first two have more than 14 words

**Comment by MichaelKohler** [comment]
And in theory both requirements could be changed for Spanish explicitly if needed

**Comment by Txopi** [comment]
When the tool is opened for everyone, I'm sure we will have a lot of issues like this. I think it clearly deserves to make an effort in the Add page and show a reject reason next to each filtered sentence.

I would also put an explicit maximum of sentences to load at a time, because my first test was to paste [2.315 sentences](https://github.com/mozilla/voice-web/blob/10bcf799720f20252b92012168c850149b9dc8d2/server/data/eu/librezale01.txt) and although I wait for some minutes I got no response nor feedback at all. I think 100 sentences for example is a reasonable number.

**Comment by nukeador** [comment]
No action needed then. 14 words is reasonable for Spanish if our goal is. then under 5s recordings.
