### ISSUE TITLE
Add "undo" to go back to previous sentence in Swiping Review Tool

### ISSUE THREAD

**Issue by ppnplus** [common-voice/sentence-collector#456]
In Swiping Review Tool, when a sentence have been checked or skipped, it cannot be undone. This means that if I've accidentally swiped, pressed the wrong button, or want to change decision, I can't step back to the previous sentence and recheck it. Instead, I have to reload the page and start over from the beginning. This also means I have to carefully check for the sentence before approving or rejecting it.

I'd like the Swiping Review Tool to include the ability to undo (go back to previous sentences), so I don't have to reload the page and start over every time I made a mistake.

**Comment by MichaelKohler** [comment]
Thanka for filing this. For now it's possible to show again all skipped through the profile page, but that would not be on a single occurance. I agree that a back button on the review page would make sense indeed!

**Comment by MichaelKohler** [comment]
For skipped sentences this seems pretty straight forward.

For sentences that either got an approval or rejection, I'm not fully sure what the expected behavior would be. Let's take the following steps:

* You open the Review page
* You approve the first sentence
* On the second sentence you click on the "Back" button

Should the first sentence now show that it was initially approved and you could change it nevertheless? Or should I be all new without marking the previous approval/rejection? If you don't change it and click on "Finish review", should it take the previous approval?

I can see reasons for both behaviors, so I'm torn. @ppnplus what do you think?

**Comment by ppnplus** [comment]
@MichaelKohler Removing the previous sentence's status feels closer to what I expect. However, it may cause problem with users trying to go back many sentences (where a user must check previous sentences again.)

Having an option for users to change its behaviour is preferable.

**Comment by HarikalarKutusu** [comment]
Another idea would be using a timer before enabling swipe/keyboard actions, possibly with a duration linear to the length of the sentence.

On the other hand, that would cause unnecessary delays if the dataset is pre-checked offline and added here to get into the database, where other volunteers can accept quickly.

**Comment by MichaelKohler** [comment]
Thanks for bringing this up. The Sentence Collector now has moved to https://commonvoice.mozilla.org/write and therefore is now hosted in the main Common Voice repository. That being said, this issue is no longer relevant as that part of the review process has been fully changed.
