### ISSUE TITLE
Concept to adapt to language handling

### ISSUE THREAD

**Issue by MichaelKohler** [common-voice/sentence-collector#531]
Currently there are quite a few languages enabled on Sentence Collector that are not enabled on Common Voice itself, and most of them also have never been requested to be added. This is due to the historical decision of enabling all ISO 639-1 codes in the Sentence Collector. As contributing to not-enabled languages basically could be considered "contributing into the void" until they actually get enabled in Common Voice, we need to take care of this at this point. This also has an impact on #492.

To have a better understanding, let's start with the following tasks:

- [x] How many, and which, languages have been contributed to in SC but are not enabled on CV?
- [x] Would that mean that we can (finally) let CV handle the languages, and not have our own language list?

**Comment by HarikalarKutusu** [comment]
Here are my answers:

Answer 1: I don't know the exact list, If you can provide it, I can check.
Answer 2: CV should handle these through Pontoon + all.json

The process for adding a language to CV is:
* Asking for it
* Having the frontend translated 90%+
* Having 5000 sentences

I don't know the number in SC, but:
* Pontoon has 151 teams (added there because people asked for that language)
* CV has 152 locales (all.json), from which 85 are listed as "contributable" (contributable.json) thus people are abşe to record/listen as of now. The extra one compared to Pontoon is "eo" ...

So, for people to translate UI / add those 5000 sentences, SC should use the largest one from all.json... I don't know about "eo"...

But for people to contribute, while translating, they will also translate SC strings anyway...

**Comment by MichaelKohler** [comment]
Thanks for that. From what I can see people have contributed to the following locales, which are not on Pontoon:

- ak (5 sentences)
- gu (9 sentences)
- hy (2312 sentences) (see also #454)
- io (1 sentence)
- kn (732 sentences)
- la (4 sentences)
- lb (7 sentences)
- os (25 sentences)
- sa (5158 sentences)
- su (29 sentences)
- tig (see https://github.com/common-voice/common-voice/issues/3341)
- wo (1 sentence)
- xh (1 sentence)

Possibly we should figure out if somebody wants to officially start `kn` and `sa`. The remaining languages would probably be ok to be disabled for now until somebody wants to officially start it.

Then at this point, I think we indeed could solely rely on the info the CV repository has and we wouldn't need our own list.

> Pontoon has 151 teams (added there because people asked for that language)
    CV has 152 locales (all.json), from which 85 are listed as "contributable" (contributable.json) thus people are abşe to record/listen as of now. The extra one compared to Pontoon is "eo" ...

Are you sure it's `eo`? I can see it at https://pontoon.mozilla.org/eo/common-voice/

**Comment by HarikalarKutusu** [comment]
> Are you sure it's eo? I can see it at https://pontoon.mozilla.org/eo/common-voice/

Oh my... I need to check my glasses. It is "en" of course :)

**Comment by MichaelKohler** [comment]
Hah, that makes sense 😁 Thanks!

**Comment by MichaelKohler** [comment]
For Sanskrit and Kannada I created https://discourse.mozilla.org/t/kannada-and-sanskrit/88555/2.

The remaining questions are IMHO answered for now and follow-up issues are created for those. Therefore I'm closing this.
