### ISSUE TITLE
Create Dark Mode theme

### ISSUE THREAD

**Issue by robovoice1** [common-voice/sentence-collector#617]
Switch your mobile browser to darkmode.
Log in to your sc account.
See pic 2.
When logged into sc website, see pic1.

In both cases the mozilla logo cannot be read.
![Screenshot_20220330-234817_1](https://user-images.githubusercontent.com/92784377/160938752-5413fb3a-388f-492d-a2e9-adef6c805bfd.png)
![Screenshot_20220330-234927_1](https://user-images.githubusercontent.com/92784377/160938856-9c952382-9794-4090-9488-abd39e3ac264.png)

Pixel 6 pro
Android 12 GrapheneOS (latest beta channel)
Bromite mobile android browser
99.0.4844.77

This also is the case for cv website (moz logo and parts of robot avatar), which i filed here
https://github.com/common-voice/common-voice/issues/3644

**Comment by MichaelKohler** [comment]
How did you enable dark mode?

**Comment by robovoice1** [comment]
In Bromite options
![Screenshot_20220331-004324](https://user-images.githubusercontent.com/92784377/160943232-388a9ee5-e9a0-4646-8d35-e67cca4adb51.png)

**Comment by robovoice1** [comment]
![Screenshot_20220331-005419](https://user-images.githubusercontent.com/92784377/160944252-2eabd3ab-eb40-426b-bb99-58b56cc0793d.png)

**Comment by HarikalarKutusu** [comment]
This might help:

https://stackoverflow.com/questions/56393880/how-do-i-detect-dark-mode-using-javascript

**Comment by HarikalarKutusu** [comment]
Or just a simple trick thou quick and dirty...
```
<a href="#/en/" style="background-color: #f0f0f0;">
  <img src="https://commonvoice.mozilla.org/sentence-collector/fc9605a3cf4940476f316f8333623785.svg">
</a>
```

**Comment by robovoice1** [comment]
Thanks for the info.
Could a redesign and swap of the moz://a banner (viewable in dark/normal mode) be an option?
But you are right, this would be " nice to have", but not really a must have.

**Comment by HarikalarKutusu** [comment]
> While it then would show correctly in Bromite, it would be wrong in any other browser that doesn't apply dark theme

A common technique we use for these cases is to check the flag and show an alternate logo image, which would be the negative logo, it can be another image or you can serve the SVG from the app and change the color.

I don't see any reason for dark mode implementation if other parts are working OK (which I didn't check).

**Comment by HarikalarKutusu** [comment]
Check the dark one under the "background colors" section in this link. CV does not have its own identity AFAIK, but it is adaptable.

https://mozilla.design/mozilla/logo-usage/

**Comment by robovoice1** [comment]
![Screenshot_20220401-075914](https://user-images.githubusercontent.com/92784377/161204851-2495bced-5860-4df2-b70f-c53352fae59f.png)
Latest Firefox nightly android with Dark Reader add on.

**Comment by HarikalarKutusu** [comment]
This is CV's Logo component:

https://github.com/common-voice/common-voice/blob/a72fee0562582ecec27e4c48c4a6b0d157db08ee/web/src/components/layout/logo.tsx

It is used twice on the layout, one without "reverse" at the header, the other with "reverse" at the footer. I think it can be borrowed :)

**Comment by MichaelKohler** [comment]
Thanks for the screenshot, @robovoice1. Looks like Dark Reader add-on does very interesting things, including manipulating images on their own to [invert the colors](https://github.com/darkreader/darkreader/blob/5d9c5381511cd524822806883ba5ca3abd5e4571/src/inject/dynamic-theme/modify-css.ts#L439). Looks like that algorithm is better than what Bromite does.

However, in none of these cases anything is done by the website. This is all done either in the browser (case of Bromite) or in the add-on (Dark Reader).

> A common technique we use for these cases is to check the flag and show an alternate logo image, which would be the negative logo, it can be another image or you can serve the SVG from the app and change the color. These monochromatic logos exist for such purposes when corporate identity designs are formed.
>
> I don't see any reason for dark mode implementation if other parts are working OK (which I didn't check).

Yes, that would be the approach when a website wants to support dark mode. However currently Sentence Collector does not support anything at all. The rest is only working because of what the features/add-ons do.

If we would only "fix" the logo, we would end up in the following case:

- For users of add-ons or browser functionality that automatically inverts colors it would be fixed (for example the issue in Bromite)
- For anyone without that functionality or addons, and a light theme preference, nothing would change
- However for users with a dark theme preference, the only thing changing would be the logo. It would now show the inverted image on a white background, making it white-on-white. Only the logo would react to the dark preference, nothing else.

I hope that makes sense?

I agree that for the implementation of dark mode, the inverted SVG could be borrowed from Common Voice.

**Comment by MichaelKohler** [comment]
Thanks for bringing this up. The Sentence Collector now has moved to https://commonvoice.mozilla.org/write and therefore is now hosted in the main Common Voice repository.
