### ISSUE TITLE
Documentation - How to Cite

### ISSUE THREAD

**Issue by nesnera** [common-voice/sentence-collector#672]
It is not clear from the wording of paragraph [How to Cite](https://commonvoice.mozilla.org/sentence-collector/#/en/how-to) whether this is a citation of Common Voice or, conversely, of the sources used in the CV, or a mixture of both, I'm afraid.

**Comment by HarikalarKutusu** [comment]
@nesnera: I can see the examples there can be misleading, they are just some domain names.

You need to give a link to the resource you get the data from (obviously not Common Voice), so that it can be checked if the data is public domain / CC-0. If they are not, the data you added will be deleted because of copyright infringement.

Examples:
- Your university has a corpus creation project and the data is CC-0. You can enter that project's license page where it openly states that the data is public domain / CC-0 (e.g: CC-0 corpus from xxx project - link to license / link to the arxiv record etc)
- There is a writer who died 70 years before, and his/her works go public domain, and you scan these works and enter appropriate ones to the Sentence Collector. You can enter a link to the Wikipedia page on this writer where one can see the death year (e.g.: Public domain works of late XXX YYY - link to Wikipedia page)

Hope this helps...

**Comment by MichaelKohler** [comment]
Thanks for helping answer the question, @HarikalarKutusu . I agree that this does not necessarily become clear with the given examples and it would make sense to improve those. So I'm going to keep this issue open to do that.

Thanks for reporting this, @nesnera!

**Comment by MichaelKohler** [comment]
Thanks for bringing this up. The Sentence Collector now has moved to https://commonvoice.mozilla.org/write and therefore is now hosted in the main Common Voice repository. With this move the guidelines now live at https://commonvoice.mozilla.org/en/guidelines in the "Sentence Collection" tab. I think the phrasing there is now better and less confusing. If you disagree, please feel free to open another issue in the repo here: github.com/common-voice/common-voice/. Thanks for the help!
