### ISSUE TITLE
Profile page: Improve two labels

### ISSUE THREAD

**Issue by Txopi** [Common-Voice/sentence-collector#88]
The main menu talks about "add" and "review", but the profile page talks about "submitted" and "validated" sentences. I think profile page should say something like this:
- 999 ~~submitted~~ **added** by you.
- 999 ~~validated~~ **reviewed** by you.

**Comment by MichaelKohler** [comment]
@nukeador I agree, do you?

**Comment by nukeador** [comment]
Yep

**Comment by MichaelKohler** [comment]
Here are the lines that need to be changed for this: https://github.com/Common-Voice/sentence-collector/blob/fde0444e876f00ef706a91c9cf9f9d36d00df7ca/web/src/components/pages/profile.jsx#L187

It's enough to replace the text directly, as we are not using any localization yet. For instructions on how to set up the environment locally to test this change, please refer to the [README](https://github.com/Common-Voice/sentence-collector/blob/master/README.md). I'm happy to help if somebody wants to tackle this and gets stuck along the way.

**Comment by MichaelKohler** [comment]
Additionally, when nothing has been done yet, we show the following sentence:

> No sentences submitted or validated, try reviewing some sentences now?

This should read "No sentences submitted or reviewed, .."

**Comment by amanriquez** [comment]
Hi! I'm a beginning bootcamp student, really looking to get into open source and this looks like a first issue I could handle...I'd really like to help. Could I do this? could you give me a little more guidance?

**Comment by MichaelKohler** [comment]
Hi @amanriquez, great to hear that! Yes, this issue is currently not being worked on, so this would be a great candidate for you!

First of all, it would make sense to get the website running locally, so you can also test your fixes. The https://github.com/Common-Voice/sentence-collector/blob/master/README.md has some documentation on how to set up the local environment. There might be some parts missing or unclear, so don't hesitate to ask me any questions here :)

Once you have the setup running locally, we can move forward by fixing this here. https://github.com/Common-Voice/sentence-collector/issues/88#issuecomment-452675259 has some pointers, but also here, feel free to ask anything you need.

Happy to help if you run into any problems!

**Comment by MichaelKohler** [comment]
> gyp info spawn args   '-Goutput_dir=.' ]
> No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
> No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
> No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
> gyp: No Xcode or CLT version detected!
> gyp ERR! configure error 

This looks like XCode/CLT is not installed. Have you installed a copy of XCode? If not, you'll need to do so, otherwise some dependencies can't be built. If you already have XCode, you probably also need to run `xcode-select --install` to install the XCode command line tools. Can you try to install XCode, install the command line tools and then run `yarn` again and see if everything installs correctly?

**Comment by amanriquez** [comment]
Ok there it goes..let me know if I did this right!
